version: '3.3'

services:
  app:
    image: python:3.11.2
    build:
      context: .
    volumes:
      - .:/app
    depends_on:
      - db
    # network_mode: 'host'
    ports:
      - ${PORT}:${PORT}
    command: bash -c "cd app
                      && pip install poetry
                      && poetry install
                      && make start"

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./database.sql:/docker-entrypoint-initdb.d/001.sql
    ports:
      - ${DB_PORT}:${DB_PORT}
